### ISSUE TITLE
Slwf-08

### ISSUE THREAD

**Issue by Idaho947** [smlight-tech/slwf-08#4]
Hello,

Just buy a slwf-08 and don't understand how it works.

I flash the key with this yaml :

```
substitutions:
  name: "tvesphome"
  friendly_name: "tvesphome"
  project_name: "SMLIGHT.SLWF-08-HDMI"
  project_version: "1.0-Palakis"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "HDMI-AP"
    password: "slwf0800"
  manual_ip:
    static_ip: 192.168.1.145
    gateway: 192.168.1.1
    subnet: 255.255.255.0

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: "w4m5vYexKMiKvExT6kvuDkE7XywLWvVDgsLsksnOt0A="
  services:
    - service: hdmi_cec_send
      variables:
        cec_destination: int
        cec_data: int[]
      then:
        - hdmi_cec.send:
            destination: !lambda "return static_cast<unsigned char>(cec_destination);"
            data: !lambda "std::vector<unsigned char> charVector; for (int i : cec_data) { charVector.push_back(static_cast<unsigned char>(i)); } return charVector;"

ota:
  - platform: esphome

web_server:
  port: 80

# Enable logging
logger:

external_components:
#  - source: github://johnboiles/esphome-hdmi-cec
  - source: github://Palakis/esphome-hdmi-cec

dashboard_import:
  package_import_url: github://smlight-tech/slwf-08/esphome-configs/slwf-08-Palakis.yaml

hdmi_cec:
  pin: GPIO14
  address: 0x05
  physical_address: 0x4000
  osd_name: "SLWF-08-HDMI" # Optional. Defaults to "esphome"  
  promiscuous_mode: false # Optional. Defaults to false  
  monitor_mode: false # Optional. Defaults to false  
  on_message:
    - opcode: 0x36 # opcode for "Standby"
      then:
        logger.log: "Got Standby command"
        # Respond to "Menu Request" (not required, example purposes only)
    - opcode: 0x8D
      then:
        hdmi_cec.send:
          # both "destination" and "data" are templatable
          destination: !lambda return source;
          data: [0x8E, 0x01] # 0x01 => "Menu Deactivated" 

button:
  - platform: template
    name: "Turn everything on"
    on_press:
      - hdmi_cec.send:
          destination: 0xF # or 0xF for Broadcast
          data: [0x04] # "Image View on
  - platform: template
    name: "Turn everything off"
    on_press:
      - hdmi_cec.send:
          destination: 0xF
          data: [0x36] # "Standby" opcode
  - platform: template
    name: "Turn active source"
    on_press:
      - hdmi_cec.send:
          destination: 0xF # Broadcast
          data: [0x82] # "Power on" opcode
  - platform: template
    name: "Mute"
    on_press:
      - hdmi_cec.send:
          destination: 0xF # Broadcast
          data: [0x43] # "Mute" opcode          
  - platform: template
    name: "Volume Down"
    on_press:
      - hdmi_cec.send:
          destination: 0xF # Broadcast
          data: [0x42] # "Volume Down" opcode                   
  - platform: template
    name: "Volume up"
    on_press:
      - hdmi_cec.send:
          destination: 0xF # Broadcast
          data: [0x41] # "Volume up" opcode   

```
See that in log when i use the bouton on my home assistant. Nothing happen and see that in log :

```
[20:02:18][D][button:010]: 'Mute' Pressed.
[20:02:18][D][hdmi_cec:203]: sending frame: 5F:43
[20:02:18][D][hdmi_cec:225]: HDMICEC::send(): frame sent and acknowledged
[20:02:18][W][component:239]: Component api took a long time for an operation (62 ms).
[20:02:18][W][component:240]: Components should block for at most 30 ms.
```
See that when I press a bottom on my tv remote
```
[20:12:07][E][hdmi_cec:235]: HDMICEC::send(): send failed after five attempts
[20:12:07][W][component:239]: Component hdmi_cec took a long time for an operation (209 ms).
[20:12:07][W][component:240]: Components should block for at most 30 ms
```

Can you help me ?
